### ISSUE TITLE
Not visible questions of subsections when debug mode enabled

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#110]
Debug mode should allow to see all questions within the form, however this is not true for demonstrated questions.

A/C:
- whole provided form is tested for disabled questions whether they work with debugMode=true correctly.

**Comment by blcham** [comment]
![image](https://user-images.githubusercontent.com/3962237/157321994-d20b9d5c-e3ff-4f8d-9972-ce4c8ab83f11.png)

![image](https://user-images.githubusercontent.com/3962237/157323440-d513f0aa-c6d7-474e-ae48-4d598bffaae8.png)

Tested on the form:
[form1.json.gz](https://github.com/kbss-cvut/s-forms/files/8209555/form1.json.gz)

**Comment by LaChope** [comment]
@blcham is it acceptable to leave all irrelevant questions interactive? That would be the simplest solution to cover all case scenarios

**Comment by blcham** [comment]
Not sure what you mean by that ... you should not be able to add/change the value of the irrelevant question and you should be able to visually distinguish that it is irrelevant

**Comment by LaChope** [comment]
@blcham sorry it was my bad, I forgot to mention that you have to click on the slider like so:
![image](https://user-images.githubusercontent.com/57750426/157907400-c1ef1c93-dd9c-40f8-abd5-c2a2589e62e3.png)

By clicking here you can expand the question.

**Comment by blcham** [comment]
So you are saying it worked, but i did not realize that I need to click to the slider, right ?

But if it is not irrelevant, you can open it by clicking to header. It makes sense to have it same way, if is not too hard to implement. What do you think ? (This debug mode i want to use also for non-developers, to see full range of questions that are within form, so I am afraid that they would not find out that they can open it). On the other hand if it is very hard to implement, i don't want to waste too much time there.

**Comment by LaChope** [comment]
@blcham I thought this is meant for developers but if users need to use it too, yes it makes sense to let them click on the header. It was easy fix :)

**Comment by blcham** [comment]
> @blcham I thought this is meant for developers but if users need to use it too, yes it makes sense to let them click on the header. It was easy fix :)

Yes at first, i thought that it would be only for developers, but that changed. If user is building a form, it is nice to show him what questions are hidden as well.
