### ISSUE TITLE
Automate Prettier

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/s-forms#133]
I suggest the solution:

Must:

[1] we must find out at some point that we committed code that is not "pretty". (Pull request with netlify is not best but ok)
[2] check and formatting fix should be executable as script in package.json, see e.g. https://github.com/opendata-mvcr/mission-control/blob/main/package.json
[3] we should have other things, later on, to check as well, like failing tests, https://www.jslint.com/, etc ...

Nice to have:

[4] Ideally, we should find out in IDE before committing. Isn't this plugin doing that https://github.com/opendata-mvcr/mission-control/blob/main/package.json

So here is a workflow that I suggest:

- user edits js files
- he either uses automatic formating with Prettier or does it manually with a dedicated shortcut (Alt-Shift-Control P)
- if he tries to commit not "pretty" files, he finds out if he installed husky extension
- if husky not installed, he find out in pull request [1] [4] 
- user can check/fix the formating of all files by npm script [2,3]

Let me know about the workflow you suggested.

Features of [Prettier plugin for Intellij Idea](https://plugins.jetbrains.com/plugin/10456-prettier/):
- formating files only (cannot format only selected code)
   - automatic formatting on save
   - manual formating on short-cut (not same as regular one -- Alt-Shift-Control-P)
- NO real-time seeing bad format
- NO formatting of selected code

A/C: 
- Prettier plugin and workflow is described in development notes 
- say a preferred variant of Prettier

**Comment by blcham** [comment]
> Prettier should be run before each commit.

This ticket is not very well specified so let's do specify it, I will change it in the description.

**Comment by LaChope** [comment]
I found a workflow that would prevent to commit if tests fail or formatting is wrong and show what files are faulty:
![image](https://user-images.githubusercontent.com/57750426/162434639-2a0740ca-c87e-4a34-a31c-609209411c30.png)

Is it too much to completely prevent to commit, should it be possible to commit anyway and just warn?

**Comment by blcham** [comment]
Well to me it seems critical to find out how good is support in intellij idea. I feel it is very important to understand what are pros and cons of the approach ... we might have even both approaches available and time will show ... if we have this analyzed we can revise in half a year ..

**Comment by blcham** [comment]
To say my opinion, it seems very good in many senses, on the other hand running tests might take quite long.

**Comment by LaChope** [comment]
@blcham I am not sure to understand what do you mean by how it is supported in the IDE?

Otherwise, Here are the pros and cons I see with this approach:

Use `  "lint-staged": {
    "**/*": [
      "npm run test",
      "npm run prettier:check"
    ]` along with husky to run tests and check format on every commit.

- Pros: 
-Very consistent code 
-Tests will be run before pushing the commits => will prevent to fail github action to publish npm package


- Cons:
-Will be long to commit as tests will be run every time
-Can be frustrating for new people involved in the project as they will probably not understand at first why commit fails


Alternative approaches would be:

- Only run `prettier:check` on pre-commit without tests
- Only warn instead of fail in case of faulty test or not formatted file

**Comment by blcham** [comment]
> I am not sure to understand what do you mean by how it is supported in the IDE?

This means that there might be Intellij Idea plugin that reads prettier configuration files and warns you while you are editing files that your formating is not correct.
