### ISSUE TITLE
Typeahead list is hidden behind bottom of a section

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#15]
Typeahead list is not correctly visualized in special cases. It happens when it is located at the bottom of a section, see the attachment.
![Selection_197](https://user-images.githubusercontent.com/3962237/93405100-5c8bd800-f88c-11ea-8ea7-d219047298eb.jpg)

**Comment by tomasklim** [comment]
I cannot replicate.
Check that you import s-forms styles correctly

`import 's-forms/css/s-forms.min.css';`

And that you do not override this css 
`.accordion > .card {
  overflow: visible;
}`

![Screenshot 2020-09-23 at 16 36 18](https://user-images.githubusercontent.com/33235762/94027437-20400680-fdbb-11ea-803e-4ae9a386f58f.png)

**Comment by blcham** [comment]
cannot reproduce
