### ISSUE TITLE
Answerable wizard step is not visualized

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#159]
Wizard-step questions with following layout classes are not correctly visualized:
```
"wizard-step"
"section"
"answerable"
"checkbox"
```

Within this set up no checkbox is shown.
![image](https://user-images.githubusercontent.com/3962237/180647645-206f32b0-67d4-49a2-80ca-2b39844a7d0f.png)

Note, that there the code should be synchronized with https://github.com/kbss-cvut/s-forms-components/blob/master/src/components/WizardStepComponent.jsx. **Maybe, WizardStepComponent should extend Question which is not happening in SForms nor SForms Components library ?**
BTW, WizardStepComponent to me is almost same thing as Section, just "dark-blue" header insted of "light-blue" header. So maybe Question should have just some `props` / `className` for that ?

A/C:
- wizard-step show answerable question
- works correctly even in SForms Components

**Comment by blcham** [comment]
https://github.com/kbss-cvut/s-forms/pull/160 contains current workaround:

**Comment by blcham** [comment]
Current state: workaround is applied but **the issue is not fixed yet**.

**Comment by blcham** [comment]
![image](https://user-images.githubusercontent.com/3962237/182142836-6cf695b9-9b0b-481e-8037-f693e138f79f.png)

**Comment by LaChope** [comment]
Note: I did not extend Question component in #163 and made composition instead as inheritance is considered [bad practice in React](https://reactjs.org/docs/composition-vs-inheritance.html)
