### ISSUE TITLE
Improve tests for Question component

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/s-forms#171]
New tests should be created to cover:
- Question Layout / Style when:
  - Main color
  - Emphasized
  - Regular
- Question is appropriately collapsed / expanded
- Show irrelevant questions when debug mode is on or starting-question-id is assigned
- Hide irrelevant questions when debug mode is off
- Icons are properly attached to Question

**Comment by LaChope** [comment]
@blcham you can check last commit [fd24c03](https://github.com/kbss-cvut/s-forms/commit/fd24c032c1bc94873957e611909b38664af3f3c8) if you want to have a first look

**Comment by blcham** [comment]
> @blcham you can check last commit [fd24c03](https://github.com/kbss-cvut/s-forms/commit/fd24c032c1bc94873957e611909b38664af3f3c8) if you want to have a first look

Thanks, looks nice.

**Comment by blcham** [comment]
Closed by https://github.com/kbss-cvut/s-forms/pull/163.
