### ISSUE TITLE
Investigate current performance issues

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#187]
We need to cover following cases :

1) Image-ine that we are opening already saved form. Section-1 and section-2 is closed by default and you load form and open section-2 which due to question-1.1. contains question-2.1 that is relevant:
![image](https://user-images.githubusercontent.com/3962237/199461492-1bd59db4-7506-4e9a-b9f2-5ad10e547811.png)

Related to: https://github.com/kbss-cvut/s-forms/issues/181

**Comment by blcham** [comment]
To investigate performance we can use:
[The Definitive Guide To Profiling React Applications](https://blog.openreplay.com/the-definitive-guide-to-profiling-react-applications/)


https://forums.meteor.com/t/solved-violation-message-handler-took-n-ms/58046

**Comment by LaChope** [comment]
Also to consider for even better performance after [fce0dce](https://github.com/kbss-cvut/s-forms/commit/fce0dcefbc0eede6c3db9aec43a5a93f6571fa38):

- https://reactjs.org/docs/optimizing-performance.html#virtualize-long-lists
- https://github.com/bvaughn/react-window
