### ISSUE TITLE
Improve show specific question

### ISSUE THREAD

**Issue by tomasklim** [kbss-cvut/s-forms#22]
By @blcham
 ```
We should expand the section whenever possible.

For the other cases:
For a long time, I am thinking of a "debug mode", where you would be able 
to see all the questions but hidden ones you would see differently (e.g. with 50% transparency and read-only). 
The same style could be used to show hidden question within this case -- 
thus the question and all its hidden parents would be shown differently 
and the form would navigate to the question anyway.

I understand hidden and not-relevant as a same case.
```

Right now if you navigate to question which is in collapsed section, you cannot see the question.
You also cannot see hidden and not relevant questions.

**Comment by blcham** [comment]
To see how it woks see `TestApp.jsx`  and search for `startingQuestionId`.

**Comment by blcham** [comment]
Possibly irrelevant questions should be shown in two scenarios:
- show chosen question and jump to it + highlight
- show all questions within a section

In case the question is irrelevant:
- we should be able to visually differentiate it (50% transparency seems like a good idea). 
- it should be read-only

Consider:
- show questions only in the section where I am (in-focus hotkeys?)  as there could be too many questions
- aspect oriented way (hoc, prototypes)

Issues to solve:
- if answerable section is not answered then we still want to have option to expand/collapse it manually

**Comment by blcham** [comment]
2

**Comment by blcham** [comment]
- splitting this issue, thus closing in favor of #84.
