### ISSUE TITLE
Components in storybook cannot be selected in chrome dev tools

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#233]
It is not possible to select components in storybook which can be simulated at [live s-forms demo using storybook](https://s-forms-kbss.netlify.app/):
![image](https://github.com/kbss-cvut/s-forms/assets/3962237/b72092dd-4bbe-4349-bdbd-52bf928de305)

**Comment by LaChope** [comment]
@blcham I created new React App and added Storybook to it, there is the same issue so at least it means it **does not** come from our side (s-forms and s-forms-components).

![image](https://github.com/kbss-cvut/s-forms/assets/57750426/98706259-d88e-40d5-b990-2b3622b8c05d)

**Comment by LaChope** [comment]
@blcham should we close this issue with the workaround you showed me?

**Comment by blcham** [comment]
Sure, closing the issue as we have here a **reasonable workaround**: 

![image](https://github.com/kbss-cvut/s-forms/assets/3962237/d5df5786-bf34-404d-97a7-c17455052f36)
