### ISSUE TITLE
Tree autocomplete does not allow to select values by keyboard

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#258]
- we might use the original component for autocomplete (react-select) for simple values  (having something like layout-class "simple-typeahead"), but only in case if the old react-select component worked fine

@LaChope

**Comment by LaChope** [comment]
Here is the ticket for removing Select component: https://github.com/kbss-cvut/s-forms/issues/218

**Comment by LaChope** [comment]
@blcham I need to better understand the use case.

1. Does this need to work for record-manager-ui (so in the branch `downgrade-react-17`)?
2. Does it need to work for the tree also or only without tree?

**Comment by LaChope** [comment]
Simple typeahead should have flag: ` FLAT_TYPEAHEAD: "flat-typeahead"`

**Comment by LaChope** [comment]
@blcham PR was created there https://github.com/lecbyjak/intelligent-tree-select/pull/73

**Comment by LaChope** [comment]
@blcham intelligent-tree-select is using virtualization (via react-window dependency), this is why the focus is lost when navigating with keyboard. Here is interesting issue to follow: https://github.com/bvaughn/react-window/issues/650

**Comment by LaChope** [comment]
@blcham We can merge this
