### ISSUE TITLE
Validation color works only on text input questions

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/s-forms#297]
@blcham FYI

**Comment by blcham** [comment]
Yes, I was just putting the issue in, but since i have it in the clipboard:
![Image](https://github.com/kbss-cvut/s-forms/assets/3962237/dc9ba0ee-0ca3-4111-bf4a-10ba419e4bef)

**Comment by LaChope** [comment]
All question types are resolved except for typeahead (intelligent-tree dependency needs to be bumped), that will be handled by #301
