### ISSUE TITLE
Strange behaviour of wizard

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#323]
![image](https://github.com/kbss-cvut/s-forms/assets/3962237/e82f9783-a6b8-4274-8112-a293164aa337)

In general, we do not want this behavior.

I believe such behavior is useful only in cases where we support incremental question display (i.e., questions would be shown to the user incrementally -- when he/she enters field n, the field n+1 would be shown to him)

A/C:
- [x] it is found out if we support incremental question display
- [x] default behavior is changed so user can navigate to different tab without "Next" button
- [x] If user must use "Next button", the Wizard tab should be grayed out with a message something like: "Navigation to this tab is disabled to prevent overlooking important questions. Use form-related buttons to navigate to this TAB instead."

**Comment by LaChope** [comment]
In SForms, it is possible to click "FHA classification" without clicking "Next" first.

**Comment by LaChope** [comment]
Actually, we support incremental question. I overlooked `enableForwardSkip` option. What do you think about renaming it "enableWizardStepSkip", to make it clearer?

**Comment by blcham** [comment]
I am ok with renaming, but would like to know what it means that we support "incremental questions" :)

**Comment by LaChope** [comment]
Sorry, "incremental step" would be more appropriate. With this option, we can force user to use "Next" and "Previous" buttons to change the wizard step. IMO, if `enableForwardSkip` if disabled, it should be at least greyed out and have some tool tip. In this current step, it really looks like it is a bug.

**Comment by blcham** [comment]
I unchecked `default behavior is changed so user can navigate to different tab without "Next" button` as I believe it was not solved, leaving this ticket unresolved.

**Comment by LaChope** [comment]
> I agree, it should be grayed out with a message something like: "Navigation to this tab is disabled to prevent overlooking important questions. Use form-related buttons to navigate to this TAB instead."

I added this to A/C.
