### ISSUE TITLE
Tooltip for answers do not work

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#347]
![image](https://github.com/user-attachments/assets/2010d7c6-ebdc-404a-86df-91cea4dac3fb)

The screenshot is from an older version (4907285a0fc34fc2ee2272cf20422766793d1f4e) where it works. (I had to use `nvm use v16.20.2` to run)

**Comment by LaChope** [comment]
@blcham just FYI, I cannot reproduce the tooltip behavior, even going on https://github.com/kbss-cvut/s-forms/commit/4907285a0fc34fc2ee2272cf20422766793d1f4e, using Node 16.

**Comment by blcham** [comment]
@LaChope **sorry, I described it badly**. It work on the older version (https://github.com/kbss-cvut/s-forms/commit/4907285a0fc34fc2ee2272cf20422766793d1f4e), but you have to provide it current form2.json. 

The form2.json must contain sentence "A chef prepares and cooks food ...". Thus to reproduce :
1) checkout https://github.com/kbss-cvut/s-forms/commit/4907285a0fc34fc2ee2272cf20422766793d1f4e
2) replace form2.json from current master (i.e. from commit https://github.com/kbss-cvut/s-forms/commit/e8706192ec06df729ec55fca5b3ff0401b2f94ba)
3) `npm run dev`



I did not stress that you need to use form2.json from the main but test it on the provided commit.
