### ISSUE TITLE
Migrate to bootstrap 5

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#362]
This relates to #352. However, I tried it in Netlify, and it does not work properly:
![image](https://github.com/user-attachments/assets/a930f9f5-673b-49f9-acaa-ff576412e7d8)

Part of the task should be to go over all forms and check that they look the same (maybe `Chromatic` is exactly built for that).

A/C:
- bootstrap is migrated to version > 5
- all forms within Netlify (master branch vs. PR branch) are compared to make sure that migration worked properly

**Comment by palagdan** [comment]
@blcham

The issue could be related to the version of React Bootstrap in s-forms. I tried updating React Bootstrap first, then Bootstrap itself.

This makes sense since the input field is a React Bootstrap component.
