### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by palagdan** [kbss-cvut/s-forms#363]
While reviewing the sforms project, I found the following error in DataTimeAnswer.jsx:
![sforms-range-error2](https://github.com/user-attachments/assets/4a733832-949b-48e5-a67a-74126e7dc7a9)
![sforms-range-error](https://github.com/user-attachments/assets/785dc3c4-da6d-4e0d-905b-8ebdc16e7269)

**Comment by blcham** [comment]
@palagdan can you elaborate on what question caused it?

**Comment by palagdan** [comment]
@blcham 
In Domain specific questions:

- Diagnostic procedure
- Histological type
- LVSI
- Pre-treatment stage (taking into account imaging too)

**Comment by blcham** [comment]
@palagdan Are you sure we are still talking about `Invalid time value`?

E.g. Diagnostic procedure is defined as:
```
{
      "has-origin-type": "http://onto.fel.cvut.cz/ontologies/eccairs/aviation-3.4.0.2/a-451",
      "label": "Diagnostic procedure",
      "has-question-origin": "http://onto.fel.cvut.cz/ontologies/eccairs/model/instance#instance-288773857",
      "comment": {
        "@value": "  ",
        "@language": "en"
      },
      "@id": "http://vfn.cz/ontologies/fss-form/diagnosis-diagnostic-procedure-q",
      "has-template": "http://onto.fel.cvut.cz/ontologies/eccairs/aviation-3.4.0.2/a-451-qt",
      "@type": "doc:question",
      "has-layout-class": "type-ahead"
    },
```

There is not anything about time there.

**Comment by palagdan** [comment]
@blcham 

No, I meant "Cannot read property 'length'..." error. 

I receive an "Invalid time value" error every time I click on "Domain Specific Questions."
