### ISSUE TITLE
Allow commenting on question

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#51]
As a user, I want to be able to comment on any question. 

There should be an icon/button next to a question that would trigger commenting on it. Each comment should have a timestamp and the author of the comment.

A/C:
- user can add comment to each question (in debug mode even to irrelevant question)
- within every question it is possible to visualize multiple comments from multiple users ordered by time (the most recent first)
- each comment has timestamp and user (if available)
- "currentUser" and "users" (both of them are optional) is configured by  "SForms" component options
- already entered comments show user label if available. Otherwise it shows URL if available. On clicking new window with URL is opened.

**Comment by blcham** [comment]
12

**Comment by LaChope** [comment]
Form option: URL to user (optional), if not filled in, not visible on the comment, only timestamp.

**Comment by blcham** [comment]
Most likely it makes sense to be able to access comments from:
```
const FormQuestionsProvider = (props) => {
  const [comments, setComments] = ....
```

**Comment by LaChope** [comment]
- Change Colors
- Add scroll bar

**Comment by LaChope** [comment]
- Change Colors
- Add scroll bar

**Comment by blcham** [comment]
Already merged.
