### ISSUE TITLE
Fix issues related to merge to main branch

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#67]
- [x]  go over all relevant branches and resolve conversations that are done

    e.g. https://github.com/kbss-cvut/s-forms/pull/61
- [ ] why we removed this -- it will not show help icon correctly in show-advanced-question:

```
      <HelpIcon
          text={JsonLdUtils.getLocalized(question[Constants.HELP_DESCRIPTION], options.intl)}
           absolutePosition={false}
      />
```

- [ ] test help icon and comments icon on https://github.com/kbss-cvut/s-forms-smart-components

**Comment by LaChope** [comment]
I cannot find where this is used again:

```
      <HelpIcon
          text={JsonLdUtils.getLocalized(question[Constants.HELP_DESCRIPTION], options.intl)}
           absolutePosition={false}
      />
```

Was it in the SForms Smart Components?

**Comment by blcham** [comment]
>  go over all relevant branches and resolve conversations that are done

I see many comments that are not resolved and i tagged them with "@LaChope this is not resolved."

**Comment by blcham** [comment]
I do not see how you resolved following ponts:
> why we removed this -- it will not show help icon correctly in show-advanced-question:
> test help icon and comments icon on https://github.com/kbss-cvut/s-forms-smart-components

**Comment by LaChope** [comment]
> I do not see how you resolved following ponts:
> 
> > why we removed this -- it will not show help icon correctly in show-advanced-question:
> > test help icon and comments icon on https://github.com/kbss-cvut/s-forms-smart-components

In the Question.jsx, I added to HelpIcon `absolutePosition={false}` like so:

```
        return <HelpIcon
            text={JsonLdUtils.getLocalized(question[Constants.HELP_DESCRIPTION], options.intl)}
            absolutePosition={false}/>
      }
```

So we already set the absolute position to false in Questions and Answers. However, in show-advanced-question, if the absolute position is not specified, it will be set as true by default.

I think that having this in-line style in HelpIcon is bad practice and should be refactored anyway (if possible). We loose the control over the component because in-line style attributes *override* all other style attributes. So, if it is not known that there is such an in-line style attribute, it can be hard to know where it comes from.

**Comment by blcham** [comment]
> > I do not see how you resolved following ponts:
> > > why we removed this -- it will not show help icon correctly in show-advanced-question:
> > > test help icon and comments icon on https://github.com/kbss-cvut/s-forms-smart-components
> 
> In the Question.jsx, I added to HelpIcon `absolutePosition={false}` like so:
> 
> ```
>         return <HelpIcon
>             text={JsonLdUtils.getLocalized(question[Constants.HELP_DESCRIPTION], options.intl)}
>             absolutePosition={false}/>
>       }
> ```
> 
> So we already set the absolute position to false in Questions and Answers. However, in show-advanced-question, if the absolute position is not specified, it will be set as true by default.
> 
> I think that having this in-line style in HelpIcon is bad practice and should be refactored anyway (if possible). We loose the control over the component because in-line style attributes _override_ all other style attributes. So, if it is not known that there is such an in-line style attribute, it can be hard to know where it comes from.

So assume you tested it in s-forms-smart-components and it works correctly right ?

You are saying it is bad practice, I agree. Can you propose fix in new ticket pointing to s-forms-smart-components project ?

Alternativelly:
- discuss the detail of implementation proposal in ticket 
- propose it through 2 pull requests that will be linked to the ticket
