### ISSUE TITLE
Refactor code for better readability

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#68]
Consider resolving some of the issues:

- [posponed]  // TODO make util function
- [x] bad practice
    Col className="no-padding-right"
- [x] Row/Coll issue 
    WizzardStep
        - Why Row / Col ?
    Question.jsx 
        - Why Row / Col ?
- [x] choose wether "em" or "rem" -- consider to replace all "px"
    .comment-list-items {
        padding-top: 20px;
    }

**Comment by LaChope** [comment]
@blcham I do not think it is possible to make a util function of `getComments` / `getAnswers`... because they are different.

**Comment by blcham** [comment]
> @blcham I do not think it is possible to make a util function of `getComments` / `getAnswers`... because they are different.

I believe there is ... but I suggest to leave it for next time, its little more  complicated than i expected :)
