### ISSUE TITLE
Fix issues from review 2021-11-02

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#69]
Fix minor issues from the review:
- [x] return "..." + commentAuthor.split('/people/').pop();
    - the url can look totally different e.g. http://cvut.cz/students/max-chopart
    - so the way to do it is to take so called localFragment which is last part of the url separated by "/" or "#"
- [x] constants for this
    - questionComments: "disable", // enable | <disable> | onHover
- [x] empty message
- [x] bug: when there is a label of user we need to show it
      users: [
          {id: "http://fel.cvut.cz/people/max-chopart", label: "Max Chopart"},
          {id: "http://fel.cvut.cz/people/miroslav-blasko", label: "Miroslav Blasko"}],
      currentUser: "http://fel.cvut.cz/people/max-chopart",
- [x] follow up conventions e.g.
    const renderQuestionHelp = Question._renderQuestionHelp(question, options);
    
- [x] way to implement ordering 
      icons: [
        { id: "questionComments", behaviour: "enable"},
        { id: "questionHelp", behaviour: "enable"}
      ],
- [x] we are duplicating _renderIcons() in question and WizzardStep
    - go over my comments
- [x] #70
- [x] #71
- [x] #72

**Comment by blcham** [comment]
I dont understand where is this comment implemented:
> so the way to do it is to take so called localFragment which is last part of the url separated by "/" or "#"

**Comment by blcham** [comment]
I converted other stuff to issues, so let's do it in separate tickets.

**Comment by LaChope** [comment]
> I dont understand where is this comment implemented (it is marked as done):
> 
> > so the way to do it is to take so called localFragment which is last part of the url separated by "/" or "#"

The label of the author is now displayed instead of the last fragment of the url, which means we do not need to get the last fragment of the url to display, but only the label:

```
    const getAuthorLabel = () => {
        const users = options.users;
        const currentUser = options.currentUser;
        const currentUserId = users.find(c => c.id === currentUser);

        if (props.author) {
            return "... " + currentUserId.label;
        }
        return UNKNOWN_AUTHOR;
    }

    const getFullAuthor = () => {
        if (props.author) {
            return props.author[Constants.HAS_AUTHOR];
        }
        return UNKNOWN_AUTHOR;
    }
```

**Comment by blcham** [comment]
@LaChope 

Forms are saving only reference (= URL) of people that are working on them. This must be like that because you can change your name, your age changes, your affiliation to some organization change .... Thus reference is ok here. As a consequence following 4 situations may happen:

- user is known (we have URL of the user)
   - A) we don't have information about the user ===> **show only fragment of url**
   - B) we have information about the user such as its label (first name + last name)   ===> **show the label**
- C) user is unknown (e.g. application that uses forms does not require login) ==>  **we show something like "unknown user"/"annonymous" or whatever we already agreed**

Thus A), B), C) must be covered.
