### ISSUE TITLE
you can show multiple comment dialogs and since you cannot move them it is an issue

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#70]

**Comment by LaChope** [comment]
@blcham I was thinking to use a library called framer motion, which makes animations handling really easy in React (in this case I would use https://www.framer.com/docs/examples/#drag).

It would be nice to implement such a library to make S-Forms with nice animations. However, that could be hard to maintain overtime. Do you recommend to avoid it or is this acceptable?

**Comment by blcham** [comment]
> @blcham I was thinking to use a library called framer motion, which makes animations handling really easy in React (in this case I would use https://www.framer.com/docs/examples/#drag).
> 
> It would be nice to implement such a library to make S-Forms with nice animations. However, that could be hard to maintain overtime. Do you recommend to avoid it or is this acceptable?

Since library does not have many dependencies, i guess it is ok.

**Comment by blcham** [comment]
I feel like we can close this issue @LaChope  right ?

**Comment by LaChope** [comment]
Yes, it can be closed.
