### ISSUE TITLE
Design and change naming convention for handlers

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#71]

**Comment by LaChope** [comment]
@blcham 
Here is what I was using as convention for handlers: When an event attribute uses  `on` prefix, I would simply add `handler` prefix to it (e.g. `onChange` => `onChangeHandler`; `onDeleteComment` => `onDeleteCommentHandler`). 
However, I found recently that there are some issues with such convention:
- If there are more than one similar events, it does not work anymore (e.g. `onChange` event is used several times within the same component, but handlers are different)
- It can be tedious and non readable to have such long name for handlers

So here is my thought:

- **For Props**
add prefix `on`

- **For Handlers**

1. Replace `on` by `handle` for prefix
2. Add `noun` 
3. Add `verb` sufix
(e.g. `onChange` => `handleFormChange`; `onCommentDelete` => `handleCommentDelete`)

**Comment by blcham** [comment]
I agree.

**Comment by LaChope** [comment]
Can we close the issue?

**Comment by blcham** [comment]
@LaChope well it makes sense to apply the design to the code and make pull request for that.

A/C:
- all handlers are named as suggested above
