### ISSUE TITLE
Icons as separated components

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#74]
Each icon should have functionality separated within a component. Behaviour of those components should be inherited from shared component/function.

Thus you should be possible to create Icon as follows:
```
const icon  = options.find(i => i.id === "questionComments")
<QuestionCommentIcon  ...icon onChange={this.onCommentChange}>
```

**Comment by blcham** [comment]
In what state is this ticket? @LaChope

**Comment by LaChope** [comment]
Priority changed. Ignored.
