### ISSUE TITLE
Initial input length should not limit width of label

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#82]
This is example if I use property:
```
http://onto.fel.cvut.cz/ontologies/form-layout/has-initial-input-length: 6
```
![image](https://user-images.githubusercontent.com/3962237/145497242-c93b1564-9a9c-4c11-99b9-b7e33ae1f191.png)

This is same example if i don't use `has-initial-input-length` property:
![image](https://user-images.githubusercontent.com/3962237/145497467-be2b05fe-73f4-40ae-9e2e-7cee4595c408.png)

Note, after implementation test also unit-of-measure question that it works correctly:

![image](https://user-images.githubusercontent.com/3962237/145497765-6f43ad39-84ca-4f18-af1f-c2384e8357c5.png)

**Comment by LaChope** [comment]
@blcham I cannot reproduce it, is it in s-forms or s-forms-smart-components ?
