### ISSUE TITLE
Support show irrelevant question 

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#84]
We are able to "show specific question", but only ones that are relevant w.r.t. entered data. We should support "show specific question" for irrelevant questions as well -- i.e. we should be able to jump and highlight any question within the form.

The current state of implementation of "show specific question":
- we cannot jump to a question within a collapsed session (even if it is relevant)
- we cannot jump to a question that is hidden within a form

For reference to implementation see `TestApp.jsx` and search for `startingQuestionId`.

Issues to solve:
- if answerable section is not answered then we still want to have option to expand/collapse it manually

A/C:
- I am able to specify in `TestApp.jsx` any question using `startingQuestionId` and the "show specific question" would work, i.e. it jumps to that question and show it to user by highlighting

**Comment by LaChope** [comment]
@blcham For irrelevant questions, should it be possible to jump on it only if debug mode is set or even if the debug mode is false?

**Comment by blcham** [comment]
> @blcham For irrelevant questions, should it be possible to jump on it only if debug mode is set or even if the debug mode is false?

We should be able to jump anytime.

**Comment by blcham** [comment]
We tested together the functionality which did not work correctly on form `turisticke_cile.json`. The issue is that it is not possible to jump to some questions.
