### ISSUE TITLE
Strange visualization of turisticke-cile.json

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#96]
Within turisticke-cile.json autocomplete tree component is very strangely visualized.

![image](https://user-images.githubusercontent.com/3962237/152063630-d196dd05-3d44-495f-aa73-85115eb4575a.png)

Please, can u find out first if this was working in some previous version (by reverting to older version)?

**Comment by blcham** [comment]
Please also check form1.json and its domain specific questions. It has similar issues with time related questions.

**Comment by LaChope** [comment]
@blcham I think I do not have the same version of turisticke-cile.json, I cannot find these questions. Also, I cannot see any issue within form1

**Comment by blcham** [comment]
Trying to add this form in here:
https://github.com/kbss-cvut/s-forms/pull/126
